### ISSUE TITLE
Modal closing is not animated

### ISSUE THREAD

**Issue by juliogarciag** [sir-dunxalot/ember-modals#13]
I figured out today that this happened after updating from 0.2.1 to 0.3.4. After some debug i found that the problem happened here: https://github.com/sir-dunxalot/ember-modals/blob/master/addon/views/modal.js#L81. The problem is that `outletBeingClosed` is `"modal"` and `this.get('outlet')` is `undefined`. After going back to 0.2.1, i found that everything worked because both `outletBeingClosed` and the `outlet` property were both `undefined`.

I followed the steps of creating a template, setting the mixin in the application route and calling `showModal` from the controller. I wanted to keep diving in the code to figure out what happened but i don't know too much about ember internals to know why the call [here](https://github.com/sir-dunxalot/ember-modals/blob/master/addon/views/modal.js#L21) returns `undefined`.

PD: My Ember version is 1.10.0 and my Ember-CLI version is 0.2.0.

**Comment by sir-dunxalot** [comment]
Great, thank you for opening the issue and looking into it. I'll get a fix up as soon as possible but would accept a PR in the meantime. I think the issue is coming from the `_listen()` method of the modal view located at `addon/views/modal.js`.

**Comment by juliogarciag** [comment]
After forking and cloning the repo and diving inside it i found that this was, in some way, my mistake. The problem was in my application template:

``` hbs
{{outlet 'modal'}}
```

This makes the call to `this.get('_parentView.name')` from the view to return `undefined`. After cloning the repo i found that in the dummy examples the code was different: They were including a name attribute on the `outlet` call. So i did this:

``` hbs
{{outlet 'modal' name='modal'}}
```

And everything started to work as expected. I will close this issue but, i think that the documentation should me more explicit. In [here](https://github.com/sir-dunxalot/ember-modals/wiki/Installation), this code:

``` hbs
{{!--app/templates/application.hbs--}}

{{outlet}}
{{outlet 'modal'}}
```

should be changed to this:

``` hbs
{{!--app/templates/application.hbs--}}

{{outlet}}
{{outlet 'modal' name='modal'}}
```

**Comment by sir-dunxalot** [comment]
Ok, thanks for looking into it further. Definitely feels like a bug to some extent. I agree with your point about the docs. I think either:
1) All outlets should be required to have a `name` attribute
2) OR we find a better way of accessing the actual outlet name without the developer needing to specify it using the `name` attribute

**Comment by rawsp33d** [comment]
:+1: We should add this to the docs/wiki, it took me a long time to find this and solve my issues.

**Comment by sir-dunxalot** [comment]
Apologies. I have updated every occurence in the documentation.

**Comment by sirvine** [comment]
For anyone on Ember 1.13.x who is having trouble with animations upon closing, hopefully this will help: https://github.com/sir-dunxalot/ember-modals/issues/25
