### ISSUE TITLE
modal controller should extend Em.Controller, not Em.ObjectController

### ISSUE THREAD

**Issue by bartocc** [sir-dunxalot/ember-modals#17]
To remove deprecation
http://emberjs.com/deprecations/v1.x/#toc_objectcontroller

**Comment by sir-dunxalot** [comment]
Agreed - thanks for the issue. Will try and get a fix up soon but given it's just a warning it's not top of my priority list. Would happily accept a PR too.

**Comment by sir-dunxalot** [comment]
Fixed by #20  - thanks again for opening the issue.

**Comment by bartocc** [comment]
you're welcome ;-)
