### ISSUE TITLE
Question about ember-modals on IE8 / plans for supporting Ember 1.13

### ISSUE THREAD

**Issue by benkonrath** [sir-dunxalot/ember-modals#25]
Hi,

I've just tried out your demo on IE8 and ran into some problems. The modal opens but isn't shown correctly. The tests are failing on IE8 but I didn't look at the errors closely yet.

I'm curious to know if supporting IE8 is something that you are interested in doing. It seems like it could be possible because the modal does show (at least somewhat) on IE8. Obviously this would only be for a version that's compatible with Ember 1.13 as IE8 will go away in Ember 2.0. For me it's ok if the solution is that I need to add a polyfill for some functionality that's missing in IE8. If this is the way to go, could you point me in the right direction for which polyfills I'd need to use?

This leads me to my next question: Are you planning to release a version that works with the Ember 1.13 libraries (ember, ember-data, ember-cli, etc)? I haven't tried your library yet in my app that uses Ember 1.13 so it might even work now. I'm asking because I saw that the demo used Ember 1.10.

Thanks, Ben

**Comment by sir-dunxalot** [comment]
Hi Ben,

I don't have plans to support IE8, especially given Ember is dropping support for IE8 too. I'd be happy to accept a PR for fixes to the current version though. It's not something I have time for right now.

I am planning on releasing a version for Ember 1.13 and beyond. This will require the modal controller to be refactored into a service and the modal views to become components. I believe Ember is deprecating the `render()` hook so I have also been considering ways to let the modal be a route or similar. Right now I'm waiting to see what routable components, etc, will look like before making those kind of changes. However, it's likely that some of the smaller updating (e.g. controller to a service) will happen before then.

**Comment by benkonrath** [comment]
Hi Duncan,

Thanks for the quick reply. I definitely understand that IE8 has a low a priority for you. Thanks for being willing to accept PRs for any IE8 improvements. 

I played around with ember-modals today (in a modern browser). Thanks for the great documentation. My app is more in the Ember 1.13 / 2.0 style (with some guesses on how the routable components will work). I was able to get the content into a modal but the style didn't apply. I don't know if this is because my application is embedded into a regular webpage or because of the changes from ember-cli 1.13. The unstyled dialog opened and closed so I suspect I'll be able to get this working with proper IE8 appropriate styles.

Thanks again for your help. I'm looking forward to seeing how you end up making this fit into the Ember 2.0 paradigm. 

Ben

**Comment by sir-dunxalot** [comment]
Ok, sounds great. If you can share an example I'll be happy to take a look at any issues you're seeing for the modern browsers.

**Comment by sir-dunxalot** [comment]
@benkonrath I did a little investigating this evening and the main issue with Ember 1.13 is the outlet `name` attribute. This addon's method of looking that up is no longer supported and didn't find a reliable fix.

You can make the following update, which will enable hide animations in 1.13:

``` js
/* app-name/views/modal.js */

import Ember from 'ember';
import ModalView from 'ember-modals/views/modal';

const { on } = Ember;

export default ModalView.extend({

  _listen: on('willInsertElement', function() {
    const modalController = this.get('controller.modal');

    modalController.on('closeModal', this, function() {
      if (!this.get('isDestroying')) {
        this.hide();
      }
    });
  }),

});
```

The only disadvantage of this is you cannot use multiple modals at once.

**Comment by benkonrath** [comment]
The problem I was seeing was probably caused by the fact that my application (and therefore the modal outlet) are not in the default root element.
http://guides.emberjs.com/v1.13.0/configuring-ember/embedding-applications/
Thanks for the 1.13 update. I don't have time to try it right now but I am following your project so see how things work out for the release compatible with Ember 1.13 / 2.0.

**Comment by sir-dunxalot** [comment]
Ok, thanks for the info. Sounds good.
