### ISSUE TITLE
Cannot open from inside component

### ISSUE THREAD

**Issue by optikalefx** [sir-dunxalot/ember-modals#26]
You get `this.showModal is not a function`. It's redundant to have to send an action outside of the component when the component is the thing responsible for this modal.

**Comment by sir-dunxalot** [comment]
It's a very good point. This addon is going to be updated to work almost exclusively with components and a service but I'm waiting to see what routable component looks like first. There will be some small updates before then (for example the modal controller becoming a service). The service would be easy to inject into components.

Do you think that would be sufficient to solve this issue?

**Comment by optikalefx** [comment]
That would be perfect. I have other injected services already, and that was the path I'll have to go down if you weren't going to make it that. I don't have experience making a service though, so it would probably take me way longer.

**Comment by sir-dunxalot** [comment]
Ok, not a problem. I think I'll get the first couple of changes released within a week and a half or two weeks. Does that fit with your time frame? And are you able to create a workaround in the meantime?

**Comment by sir-dunxalot** [comment]
If not, `this.get('targetObject').showModal('some-template-name')` should work just fine in a component.

**Comment by optikalefx** [comment]
Yea, for now i've bubbled actions up to parent controllers using `this.sendAction`.  `this.get()` doesn't make sense here b/c you can't do `this.get('controller:index')` or whatever. At least not that i'm aware of

**Comment by sir-dunxalot** [comment]
Ok. If your component is in the template of a route (i.e. `templates/index.hbs` contains the component you want to call a modal from I believe `targetObject` will work here - that references the context that the component's template is rendered in. But either way, it seems like you're got a temporary fix. I'll try to expedite the service refactor.

**Comment by optikalefx** [comment]
OH you mean literally right "targetObject'.  Ha. I'll give that a shot

**Comment by optikalefx** [comment]
So that works as long as the component is not inside another component. Which it is in my case. So I'll keep the bubbling  for the time being. Let me know when you want some testing. Thanks!

**Comment by sir-dunxalot** [comment]
Ok, good to know! And will do - thanks!

**Comment by sir-dunxalot** [comment]
This has been fixed with the rewrite in #28
