### ISSUE TITLE
Clicking on the overlay should close the modal by default.

### ISSUE THREAD

**Issue by sir-dunxalot** [sir-dunxalot/ember-modals#6]

**Comment by sir-dunxalot** [comment]
It'd be nice to have the modal close when the user hits `esc` too.

**Comment by oddnavy** [comment]
This would be a great :+1: 

How had you planned to implement it? Happy to work on the feature

**Comment by sir-dunxalot** [comment]
Hey David!

Off the top of my head, there are two easy options:
1. Listen for the click event in the modal view and see if the `event.target` is the overlay element or similar - there are a couple of different elements that wrap the modal and both can be clicked and both should close the modal.
2. Refactor the modal view into an overlay view and a modal view. Then we listen for the click event in the overlay view, which wraps the modal view.

In both cases we'd call the modal view's `closeModal` action. Binding `esc` should be more simple than the click and would, likewise, call the `closeModal` action.

I can't work on it this week but would be more than happy to review a PR and merge it in! Otherwise, I'll add the feature next week.

**Comment by sir-dunxalot** [comment]
Fixed in #9
